### ISSUE TITLE
How do I install it?

### ISSUE THREAD

**Issue by moacirrcosta** [saboya/gorm-logical-delete#3]
At the page https://grails.org/plugin/logical-delete there is a short command to install the plugin to the application, but what about this one?

I already downloaded the source code, but I don't have any clue about how to install it.

**Comment by saboya** [comment]
That's because that plugin is in the official Grails plugin repository. Mine isn't. I did submit it but my guess is that all the attention is towards Grails 3 and Grails 2 plugins submissions are not being reviewed anymore (my submission was not denied or accepted).

You have to download it and install as a in-place plugin.

**Comment by saboya** [comment]
@moacirrcosta Don't know if you still need it, but I checked the page for the plugin and it turns out it was approved, but I had to publish a version for it. It is now listed in the official repository:

https://grails.org/plugin/gorm-logical-delete

You can install it by simply adding the dependency to your projetct:

```
compile "org.grails.plugins:gorm-logical-delete:1.1"
```

Works with any Grails 2 version above (and including) 2.3.0
